### PR TITLE
Multilingual, closing #168

### LINKED ISSUE #168: Making wikibattle multilingual
As mentioned in #85 it would be cool to play _wikibattle_ in other languages than English.

I'd propose the following solution:

- Select the desired language from a list of "common" languages (Spanish, German, Russian... Maybe only wikis with more than 100k or 200k or so articles, as listed [here](https://en.wikipedia.org/wiki/List_of_Wikipedias#Detailed_list))
- Only match people with the same language (the host of private games can decide which language the game is played in)
- Take a random English article (from the top 5000) 
- Try switching to the wiki in the desired language as shown here:
image
- As the articles are popular in the English wiki, there's a high chance it'll exist in other languages. If it doesn't, repeat.
- Same goes for the "goal".
- Everything else should work just fine, shouldn't it? I haven't yet had a look into how going to the next article works in detail, but I think which wiki (en, de, ru...) we use is easily changeable.

### PR DESCRIPTION
**Pull request by Lichtschalter-5000**
Firstly:
I'll make a draft-PR for now so we can discuss this alongside me coding...
Secondly:
Sorry, I'm kind of a newbie to git - and I might need your help with this:
Why is the commit history such a mess? I only want it to show 1c47308, as this is the only commit which differs from your master... 🙁 
If you'll look in the "Network", you'll see this branch is branching of a fresh merge from your master into mine...

This fixes #168 btw.

### CODE REVIEW

**Comment by Lichtschalter-5000** [comment]
Could interest you, @brivadeneira

**Comment by goto-bus-stop** [comment]
The commit history is likely because your previous PR was done straight from the `master` branch. Then when you pull in new changes from this repo, it creates these extra merge commits. Especially when contributing to other repositories, it's generally best to work on feature branches and submit PRs from those, and keep your own `master` branch in sync with the upstream one. You can clean this up by:
- Pulling in the `master` branch from upstream (this repo)
  ```
  # may have to add a git remote for it
  git remote add upstream git@github.com:goto-bus-stop/wikibattle.git
  git pull upstream
  ```
- Resetting your local master branch to the upstream one (you'll have to be on another branch to do this)
  ```
  git branch -f master upstream/master
  ```
- Force-push that to your own repo for completeness
  ```
  git push origin master -f
  ```

And then you can get rid of the extra commits in this PR by rebasing your `multilingual` branch on your fixed `master` branch using
```
git rebase -i master
```
(that will open an editor with lines like `pick $commithash $message`, you can remove everything except the final commit which is the one specific to this branch)
and finally force-push the `multilingual` branch using `git push origin multilingual -f`.

let me know if you run into any trouble w that! :)

**Comment by Lichtschalter-5000** [comment]
Tada! 🎉 
Thanks a lot. 😊 I'll definitely stick to that feature branch thing. 😅

**Comment by goto-bus-stop** [comment]
Oops, the PRs closed because I changed the default branch name … I don't think I can retarget your PRs, so if you want to pick these up again please create a new PR 🙏

**Comment by Lichtschalter-5000** [comment]
Oh I thought it'd be because they've been inactive for so long. Yeah, I lately got quite busy but I didn't forget about it! 
At some point I'll pick it up again. 😊

**Pull request closed without merging**
